"use client";

import * as THREE from "three";
import { GLTFLoader } from "three/examples/jsm/loaders/GLTFLoader.js";
import { AMMO, ENTITY_DATA, MAPS, type AmmoId, type EntityKind, type MapId, type ShipId } from "./gameData";
import { resolveQuality, type QualityPreference, type QualityProfile } from "./game/quality/qualityProfiles";
import { GAMEPLAY_CAMERA_POLICY, resolveCameraPresentation } from "./game/camera/cameraPolicy";
import { PLAYER_SHIP_VISUALS, validateShipVisualDefinition, type ShipVisualDefinition } from "./game/visuals/shipVisuals";

type Moving = { x:number;y:number;angle:number };
type Entity3D = Moving & { id:number;kind:EntityKind;hp:number;maxHp:number;hitAt:number };
type Shot3D = { x:number;y:number;vx:number;vy:number;ttl:number;enemy:boolean;ammo:AmmoId;hit?:boolean };
type Wake3D = { x:number;y:number;ttl:number;angle:number;strength:number };
type Loot3D = { id:number;x:number;y:number };
type HealthMarker = { sprite:THREE.Sprite;canvas:HTMLCanvasElement;texture:THREE.CanvasTexture;lastHp:number;lastSelected:boolean };
type PlayerMarker = { sprite:THREE.Sprite;canvas:HTMLCanvasElement;texture:THREE.CanvasTexture;lastKey:string };
export type WorldFrame = {
  mapId:MapId; zoom:number; cameraPan:{x:number;y:number}; selectedId:number|null; destination:null|{x:number;y:number};
  shipId:ShipId; playerName:string; playerLevel:number; deckLevel:number; weaponSlots:number; expansionSlots:number;
  player:Moving & { speed:number;hp:number;maxHp:number }; entities:Entity3D[]; shots:Shot3D[]; loot:Loot3D[];
  wake:Wake3D[];
  lastHit:number;
};

type PlayerVisualRuntimeState = {
  status:"fallback"|"loading"|"kraken-attached"|"kraken-failed";
  visualId:string;
  assetUrl?:string;
  meshCount:number;
  krakenMeshAttached:boolean;
  fallbackPresent:boolean;
  playerRootAttached:boolean;
  visualRootAttached:boolean;
  activeShipId:ShipId;
  sceneGraph:{playerRoot:string;visualRoot:string;children:string[]};
  bounds?:{x:number;y:number;z:number};
  playerWorldPosition:{x:number;y:number;z:number};
  visualBoundsCenter?:{x:number;y:number;z:number};
  error?:string;
};

const PLAYER_SHIP_IDS:ShipId[]=["sovereign","tempest","ironclad","arcanum"];

const monsterKinds = new Set<EntityKind>(["kraken","serpent","leviathan","boss"]);
const clamp = (value:number,min:number,max:number) => Math.max(min,Math.min(max,value));
const mat = (color:number,rough=.72,metal=.08,emissive=0) => new THREE.MeshStandardMaterial({color,roughness:rough,metalness:metal,emissive,emissiveIntensity:emissive?0.45:0});
const loadTexture=(url:string,repeatX:number,repeatY:number)=>{const texture=new THREE.TextureLoader().load(url);texture.wrapS=texture.wrapT=THREE.RepeatWrapping;texture.repeat.set(repeatX,repeatY);texture.colorSpace=THREE.SRGBColorSpace;texture.anisotropy=8;return texture;};
const deckTexture=loadTexture("/assets/deck-wood-v1.webp",2.8,1.25),sailTexture=loadTexture("/assets/sailcloth-v1.webp",1.35,1.35);
const shipArtLoader=new THREE.TextureLoader();
const islandArtTextures={tropical:shipArtLoader.load("/assets/tropical-port-island-v1.webp"),storm:shipArtLoader.load("/assets/storm-ruins-island-v1.webp"),abyss:shipArtLoader.load("/assets/abyss-relic-island-v1.webp")};
Object.values(islandArtTextures).forEach(texture=>{texture.colorSpace=THREE.SRGBColorSpace;texture.minFilter=THREE.LinearMipmapLinearFilter;texture.magFilter=THREE.LinearFilter;texture.anisotropy=8;});
const SHIP_MAP_SCALE=.78;

function shadows<T extends THREE.Object3D>(object:T){object.traverse(o=>{if(o instanceof THREE.Mesh){o.castShadow=true;o.receiveShadow=true;}});return object;}

function facetedHullGeometry(length:number,width:number,height:number){
  const xs=[-.52,-.39,-.08,.25,.48,.57],beam=[.58,.92,1,.88,.48,0],positions:number[]=[],uv:number[]=[],indices:number[]=[];
  for(let i=0;i<xs.length;i++){const x=xs[i]*length,w=beam[i]*width,lower=w*(i===xs.length-1?0:.52);positions.push(x,0,-lower,x,0,lower,x,height,-w,x,height,w);for(let j=0;j<4;j++)uv.push(xs[i]+.52,j%2);}
  for(let i=0;i<xs.length-1;i++){const a=i*4,b=(i+1)*4;indices.push(a,b,b+2,a,b+2,a+2,a+1,a+3,b+3,a+1,b+3,b+1,a+2,b+2,b+3,a+2,b+3,a+3,a,b+1,b,a,b+1,a+1);}
  indices.push(0,2,3,0,3,1);const geometry=new THREE.BufferGeometry();geometry.setAttribute("position",new THREE.Float32BufferAttribute(positions,3));geometry.setAttribute("uv",new THREE.Float32BufferAttribute(uv,2));geometry.setIndex(indices);geometry.computeVertexNormals();return geometry;
}

function deckGeometry(length:number,width:number,thickness:number){const shape=new THREE.Shape();shape.moveTo(-length*.46,-width*.8);shape.lineTo(length*.29,-width);shape.lineTo(length*.51,-width*.28);shape.lineTo(length*.55,0);shape.lineTo(length*.51,width*.28);shape.lineTo(length*.29,width);shape.lineTo(-length*.46,width*.8);shape.lineTo(-length*.51,0);shape.closePath();const geometry=new THREE.ExtrudeGeometry(shape,{depth:thickness,bevelEnabled:true,bevelSize:1.4,bevelThickness:1.4,bevelSegments:2});geometry.rotateX(Math.PI/2);return geometry;}

function sail(width:number,height:number,color:number,ghost=false,lateen=false){
  const shape=new THREE.Shape();if(lateen){shape.moveTo(-width*.48,height*.46);shape.lineTo(width*.48,height*.3);shape.lineTo(-width*.34,-height*.5);}else{shape.moveTo(-width*.48,height*.5);shape.lineTo(width*.45,height*.38);shape.lineTo(width*.36,-height*.5);shape.lineTo(-width*.38,-height*.43);}shape.closePath();
  const geo=new THREE.ShapeGeometry(shape,5),pos=geo.attributes.position as THREE.BufferAttribute;for(let i=0;i<pos.count;i++){const x=pos.getX(i),y=pos.getY(i);pos.setZ(i,Math.sin((x/width+.5)*Math.PI)*3.6*(1-Math.abs(y/height)*.18));}geo.computeVertexNormals();
  return new THREE.Mesh(geo,new THREE.MeshStandardMaterial({color,map:sailTexture,side:THREE.DoubleSide,roughness:.9,transparent:ghost,opacity:ghost?.68:1,emissive:color,emissiveIntensity:color===0xa98de0?.12:0}));
}

function createHullWaterInteraction(length:number,width:number,subtle=false){
  const root=new THREE.Group(),foamMaterial=new THREE.MeshBasicMaterial({color:0xc8eef8,transparent:true,opacity:subtle?.18:.28,depthWrite:false,side:THREE.DoubleSide,blending:THREE.AdditiveBlending});root.name="HullWaterInteraction";
  if(!subtle){const bowCurve=new THREE.CatmullRomCurve3([new THREE.Vector3(length*.42,1,-width*.72),new THREE.Vector3(length*.57,1,0),new THREE.Vector3(length*.42,1,width*.72)]),bow=new THREE.Mesh(new THREE.TubeGeometry(bowCurve,18,1.25,6,false),foamMaterial.clone());root.add(bow);}
  for(const side of [-1,1]){const sternCurve=new THREE.CatmullRomCurve3([new THREE.Vector3(-length*.42,1,side*width*.5),new THREE.Vector3(-length*.55,1,side*width*.72),new THREE.Vector3(-length*.7,1,side*width*.96)]),stern=new THREE.Mesh(new THREE.TubeGeometry(sternCurve,12,.85,6,false),foamMaterial.clone());root.add(stern);}
  root.userData.waterInteraction=true;return root;
}

function createShip(kind:EntityKind|"player",playerClass:ShipId="sovereign",deckLevel=1){
  const player=kind==="player",data=player?ENTITY_DATA.raider:ENTITY_DATA[kind as EntityKind],boss=!player&&data.boss,ghost=kind==="ghost",heavy=kind==="frigate"||kind==="elite"||(player&&playerClass==="ironclad");
  const silhouette=player?playerClass:boss?"ironclad":kind==="scout"?"tempest":ghost?"arcanum":heavy?"ironclad":"sovereign";
  const baseScale=boss?1.2:kind==="scout"?.82:heavy&&!player?1.08:1,length=silhouette==="tempest"?112:silhouette==="ironclad"?116:silhouette==="arcanum"?108:102,width=silhouette==="tempest"?14:silhouette==="ironclad"?27:silhouette==="arcanum"?21:20,height=silhouette==="tempest"?11:silhouette==="ironclad"?20:16;
  const group=new THREE.Group();group.userData.entityRoot=true;group.userData.baseScale=baseScale*SHIP_MAP_SCALE;group.scale.setScalar(baseScale*SHIP_MAP_SCALE);
  const playerPalette=playerClass==="tempest"?{hull:0x123f49,upper:0x247985,deck:0x8c5731,trim:0x6fe7dd,sail:0xe7f4de,accent:0x43f7e8}:playerClass==="ironclad"?{hull:0x222a31,upper:0x4a555d,deck:0x704326,trim:0xe08248,sail:0xc3b79f,accent:0xff7446}:playerClass==="arcanum"?{hull:0x241b45,upper:0x5b3787,deck:0x654039,trim:0xc39cff,sail:0xa98de0,accent:0xc674ff}:{hull:0x5a2819,upper:0x9b4e27,deck:0x8c552f,trim:0xe4bd61,sail:0xf5e9cb,accent:0x45e4ef};
  const palette=player?playerPalette:ghost?{hull:0x183f49,upper:0x2f747c,deck:0x4f6b5f,trim:0x83e8dc,sail:0x91e4dc,accent:0x69fff1}:boss?{hull:0x3f1420,upper:0x7d2032,deck:0x5d3426,trim:0xe2a14c,sail:0x7d2336,accent:0xff5c36}:heavy?{hull:0x263341,upper:0x485b68,deck:0x755033,trim:0xc99f52,sail:0xd7d0b6,accent:0xffbc58}:{hull:0x3d2018,upper:0x70402a,deck:0x87552f,trim:0xba8a48,sail:0xd8d2bb,accent:0xffc766};
  const lowerHull=new THREE.Mesh(facetedHullGeometry(length,width,height),mat(palette.hull,.48,.24,ghost?0x123f46:0));lowerHull.position.y=3;group.add(lowerHull);
  const upperHull=new THREE.Mesh(facetedHullGeometry(length*.94,width*.92,height*.55),mat(palette.upper,.54,.16,ghost?0x174a50:0));upperHull.position.set(-length*.025,3+height*.72,0);group.add(upperHull);
  const deckMaterial=new THREE.MeshStandardMaterial({color:palette.deck,map:deckTexture,roughness:.86,metalness:.03});
  const deck=new THREE.Mesh(deckGeometry(length*.93,width*.89,3.2),deckMaterial);deck.position.set(-2,6+height,0);group.add(deck);
  const keel=new THREE.Mesh(new THREE.BoxGeometry(length*.76,4,3.4),mat(palette.trim,.48,.32));keel.position.set(-length*.06,5,0);group.add(keel);
  const railMaterial=mat(palette.trim,.46,.36);for(const side of [-1,1]){const railCurve=new THREE.CatmullRomCurve3([new THREE.Vector3(-length*.43,22,side*width*.72),new THREE.Vector3(0,20,side*width*.95),new THREE.Vector3(length*.43,22,side*width*.45)]);const rail=new THREE.Mesh(new THREE.TubeGeometry(railCurve,14,1.25,6,false),railMaterial);group.add(rail);for(let p=0;p<7;p++){const t=p/6,x=-length*.4+t*length*.77,z=side*width*(.7+Math.sin(t*Math.PI)*.22),post=new THREE.Mesh(new THREE.BoxGeometry(1.7,8,1.7),railMaterial);post.position.set(x,20,z);group.add(post);}}
  const aftShape=new THREE.Shape();aftShape.moveTo(-15,0);aftShape.lineTo(13,0);aftShape.lineTo(10,15);aftShape.lineTo(-11,18);aftShape.closePath();const aftGeo=new THREE.ExtrudeGeometry(aftShape,{depth:width*1.25,bevelEnabled:true,bevelSize:1.5,bevelThickness:1.5,bevelSegments:2});aftGeo.translate(0,0,-width*.625);const cabin=new THREE.Mesh(aftGeo,mat(palette.upper,.66,.12));cabin.position.set(-length*.32,19,0);group.add(cabin);const cabinRoof=new THREE.Mesh(deckGeometry(34,width*.72,2.6),railMaterial);cabinRoof.position.set(-length*.32,39,0);group.add(cabinRoof);
  for(const side of [-1,1])for(let w=0;w<3;w++){const windowMesh=new THREE.Mesh(new THREE.PlaneGeometry(4.3,5.2),new THREE.MeshBasicMaterial({color:ghost?0x7dfff0:0xffd77c}));windowMesh.position.set(-length*.39+w*7,29,side*(width*.64+.25));windowMesh.rotation.y=side>0?0:Math.PI;group.add(windowMesh);}
  const cannonCount=(silhouette==="ironclad"?5:silhouette==="tempest"?2:4)+(player?Math.floor((deckLevel-1)/2):0);for(const side of [-1,1])for(let i=0;i<cannonCount;i++){const spread=(cannonCount-1)*Math.min(12,70/Math.max(1,cannonCount-1)),x=-spread/2+i*Math.min(12,70/Math.max(1,cannonCount-1)),carriage=new THREE.Mesh(new THREE.BoxGeometry(7,3.2,6),mat(0x56311d,.74));carriage.position.set(x,21,side*width*.5);group.add(carriage);const cannon=new THREE.Mesh(new THREE.CylinderGeometry(1.45,2.1,14,10),mat(0x171c20,.24,.92));cannon.rotation.x=Math.PI/2;cannon.position.set(x,23.5,side*(width+4));group.add(cannon);}
  if(player&&deckLevel>1){const tierColors=[0xc89553,0xe0a55f,0xd66b4e,0xf0cf67,0x68ddd7,0xb68bff];for(let tier=1;tier<deckLevel;tier++){const band=new THREE.Mesh(new THREE.BoxGeometry(length*(.62-tier*.025),1.45,2.2),mat(tierColors[tier],.32,.55,tier>=4?tierColors[tier]:0));band.position.set(-length*.04,12+tier*2.3,sideForTier(tier)*width*.91);group.add(band);}}
  const mastMaterial=mat(0x56361f,.84),mastCount=silhouette==="tempest"?1:silhouette==="ironclad"?3:2;for(let mi=0;mi<mastCount;mi++){const mx=(mastCount===1?3:mastCount===2?(mi===0?-18:21):-30+mi*30),mastHeight=(silhouette==="ironclad"?mi===1?91:78:mi===0?85:73),mast=new THREE.Mesh(new THREE.CylinderGeometry(1.55,2.35,mastHeight,10),mastMaterial);mast.position.set(mx,21+mastHeight/2,0);mast.rotation.z=silhouette==="tempest"?-.08:0;group.add(mast);const canvas=sail((mi===0?43:36),(mi===0?49:40),palette.sail,ghost,silhouette==="tempest");canvas.position.set(mx+4,56,1);canvas.rotation.y=-Math.PI/2;canvas.rotation.z=silhouette==="tempest"?-.12:0;group.add(canvas);const yard=new THREE.Mesh(new THREE.CylinderGeometry(.8,1.05,49,8),mastMaterial);yard.position.set(mx,69,0);yard.rotation.x=Math.PI/2;yard.rotation.z=silhouette==="tempest"?-.22:0;group.add(yard);const flagShape=new THREE.Shape();flagShape.moveTo(0,0);flagShape.lineTo(19,3);flagShape.lineTo(13,-4);flagShape.lineTo(19,-10);flagShape.lineTo(0,-8);const flag=new THREE.Mesh(new THREE.ShapeGeometry(flagShape),new THREE.MeshStandardMaterial({color:palette.accent,side:THREE.DoubleSide,roughness:.72}));flag.position.set(mx,98,2);flag.rotation.y=-Math.PI/2;group.add(flag);}
  const bowsprit=new THREE.Mesh(new THREE.CylinderGeometry(1.2,2,55,8),mastMaterial);bowsprit.rotation.z=Math.PI/2.12;bowsprit.position.set(length*.53,28,0);group.add(bowsprit);
  const figurehead=new THREE.Mesh(new THREE.ConeGeometry(silhouette==="ironclad"?5:3.6,18,5),railMaterial);figurehead.rotation.z=-Math.PI/2;figurehead.position.set(length*.59,20,0);group.add(figurehead);
  if(silhouette==="tempest"){for(const side of [-1,1]){const blade=new THREE.Mesh(new THREE.BoxGeometry(42,2.4,7),mat(0x1b626a,.38,.46));blade.position.set(4,11,side*(width+6));blade.rotation.y=side*.08;group.add(blade);}}
  if(silhouette==="ironclad"){for(const side of [-1,1])for(let i=0;i<5;i++){const armor=new THREE.Mesh(new THREE.BoxGeometry(19,11,3.2),mat(i%2?0x313a40:0x4b5154,.27,.9));armor.position.set(-39+i*20,14,side*(width+2));armor.rotation.z=(i-2)*.018;group.add(armor);}const ram=new THREE.Mesh(new THREE.ConeGeometry(6,35,5),mat(0x292f32,.22,.95));ram.rotation.z=-Math.PI/2;ram.position.set(length*.68,8,0);group.add(ram);}
  if(silhouette==="arcanum"){for(const side of [-1,1]){const relicRail=new THREE.Mesh(new THREE.TorusGeometry(13,2.2,6,28,Math.PI*1.35),mat(0x9d67ff,.24,.32,0x6a32b8));relicRail.position.set(6,18,side*(width+8));relicRail.rotation.set(Math.PI/2,0,side>0?.5:-.5);group.add(relicRail);for(let i=0;i<3;i++){const crystal=new THREE.Mesh(new THREE.OctahedronGeometry(4.8-i*.5),mat(0x9d67ff,.24,.18,0x6a32b8));crystal.position.set(-22+i*22,31,side*(width*.82));group.add(crystal);}}}
  const riggingMaterial=new THREE.LineBasicMaterial({color:0x493629,transparent:true,opacity:.72});for(const z of [-width*.68,width*.68]){const mastX=mastCount===1?3:mastCount===2?-18:0,rigging=new THREE.Line(new THREE.BufferGeometry().setFromPoints([new THREE.Vector3(-length*.42,24,z),new THREE.Vector3(mastX,102,0),new THREE.Vector3(length*.56,27,z*.2)]),riggingMaterial);group.add(rigging);}
  const lantern=new THREE.PointLight(player?palette.accent:boss?0xff542e:0xe0a94d,2.8,125);lantern.position.set(-length*.43,31,0);group.add(lantern);const glow=new THREE.Mesh(new THREE.OctahedronGeometry(3.2),new THREE.MeshBasicMaterial({color:palette.accent}));glow.position.copy(lantern.position);group.add(glow);
  const waterInteraction=createHullWaterInteraction(length,width);group.add(waterInteraction);group.userData.waterInteraction=waterInteraction;
  return shadows(group);
}

function sideForTier(tier:number){return tier%2===0?-1:1;}

function createKraken(kind:EntityKind){
  const group=new THREE.Group(),boss=kind==="boss"||kind==="leviathan",purple=mat(kind==="serpent"?0x246f68:kind==="leviathan"?0x233f52:0x502a70,.42,.16,kind==="serpent"?0x0b3b38:0x151033);
  if(kind==="serpent"){
    const curve=new THREE.CatmullRomCurve3([new THREE.Vector3(-105,5,-17),new THREE.Vector3(-72,9,21),new THREE.Vector3(-35,12,-18),new THREE.Vector3(2,17,13),new THREE.Vector3(39,22,0)]),body=new THREE.Mesh(new THREE.TubeGeometry(curve,52,13,14,false),purple);group.add(body);
    const head=new THREE.Mesh(new THREE.SphereGeometry(24,20,14),purple);head.scale.set(1.35,.72,.88);head.position.set(55,22,0);group.add(head);
    const snout=new THREE.Mesh(new THREE.ConeGeometry(15,33,6),purple);snout.rotation.z=-Math.PI/2;snout.position.set(80,20,0);group.add(snout);
    for(let i=0;i<7;i++){const fin=new THREE.Mesh(new THREE.ConeGeometry(5.5,17,5),mat(0x48b2a0,.5,.12,0x123c37));fin.position.set(-72+i*20,27+Math.sin(i)*5,Math.sin(i*.8)*9);fin.rotation.z=(i%2?-.18:.18);group.add(fin);}
  }else if(kind==="leviathan"||kind==="boss"){
    const body=new THREE.Mesh(new THREE.SphereGeometry(boss?43:36,20,14),purple);body.scale.set(1.6,.7,1);body.position.y=15;group.add(body);for(let i=0;i<6;i++){const spike=new THREE.Mesh(new THREE.ConeGeometry(7,24,6),mat(0x315e69,.45,.3,0x0d5860));spike.position.set(-28+i*12,42,0);group.add(spike);}const jaw=new THREE.Mesh(new THREE.ConeGeometry(28,55,5),purple);jaw.rotation.z=-Math.PI/2;jaw.position.set(56,14,0);group.add(jaw);
  }else{
    const head=new THREE.Mesh(new THREE.SphereGeometry(34,18,14),purple);head.scale.set(1.15,.75,1);head.position.y=18;group.add(head);for(let i=0;i<8;i++){const curve=new THREE.CatmullRomCurve3([new THREE.Vector3(-8,5,0),new THREE.Vector3(-35,2,(i-3.5)*10),new THREE.Vector3(-65,-2,(i-3.5)*18)]);const tube=new THREE.Mesh(new THREE.TubeGeometry(curve,10,4.5,8,false),purple);tube.rotation.y=(i-3.5)*.06;group.add(tube);}}
  for(const side of [-1,1]){const eye=new THREE.Mesh(new THREE.SphereGeometry(4.2,10,8),new THREE.MeshBasicMaterial({color:0x75fff2}));eye.position.set(kind==="serpent"?65:30,kind==="serpent"?29:27,side*(kind==="serpent"?12:13));group.add(eye);const light=new THREE.PointLight(0x53f3ee,2.2,90);light.position.copy(eye.position);group.add(light);}
  group.userData.entityRoot=true;group.userData.baseScale=kind==="serpent"?.92:boss?1.08:1;return shadows(group);
}

function createHealthMarker(e:Entity3D){const canvas=document.createElement("canvas");canvas.width=384;canvas.height=84;const texture=new THREE.CanvasTexture(canvas);texture.colorSpace=THREE.SRGBColorSpace;texture.minFilter=THREE.LinearFilter;const material=new THREE.SpriteMaterial({map:texture,transparent:true,depthTest:false,depthWrite:false});const sprite=new THREE.Sprite(material);sprite.renderOrder=80;const marker={sprite,canvas,texture,lastHp:-1,lastSelected:false};paintHealthMarker(marker,e,false);return marker;}
function paintHealthMarker(marker:HealthMarker,e:Entity3D,selected:boolean){if(marker.lastHp===e.hp&&marker.lastSelected===selected)return;marker.lastHp=e.hp;marker.lastSelected=selected;const ctx=marker.canvas.getContext("2d");if(!ctx)return;const d=ENTITY_DATA[e.kind],ratio=clamp(e.hp/e.maxHp,0,1);ctx.clearRect(0,0,384,84);ctx.textAlign="center";ctx.shadowColor="rgba(0,0,0,.85)";ctx.shadowBlur=6;ctx.fillStyle=monsterKinds.has(e.kind)?"#8deee3":"#f8ead1";ctx.font="700 18px system-ui";ctx.fillText(d.name,192,26);ctx.shadowBlur=0;ctx.fillStyle="rgba(193,222,218,.82)";ctx.font="600 15px system-ui";ctx.fillText(`LV ${d.level}`,192,42);ctx.fillStyle="rgba(2,12,18,.88)";ctx.fillRect(68,50,248,14);ctx.strokeStyle=selected?"#ffd76b":"rgba(193,222,218,.42)";ctx.lineWidth=selected?3:2;ctx.strokeRect(68,50,248,14);const gradient=ctx.createLinearGradient(68,0,316,0);gradient.addColorStop(0,ratio>.45?"#d84c45":"#d43b35");gradient.addColorStop(1,ratio>.45?"#ff9a58":"#ff5e3f");ctx.fillStyle=gradient;ctx.fillRect(70,52,244*ratio,10);marker.texture.needsUpdate=true;marker.sprite.scale.set(selected?118:100,selected?30:26,1);}

function createPlayerMarker(){const canvas=document.createElement("canvas");canvas.width=512;canvas.height=104;const texture=new THREE.CanvasTexture(canvas);texture.colorSpace=THREE.SRGBColorSpace;texture.minFilter=THREE.LinearFilter;const material=new THREE.SpriteMaterial({map:texture,transparent:true,depthTest:false,depthWrite:false});const sprite=new THREE.Sprite(material);sprite.renderOrder=90;sprite.scale.set(144,29,1);return {sprite,canvas,texture,lastKey:""};}
function paintPlayerMarker(marker:PlayerMarker,frame:WorldFrame){const hp=Math.max(0,Math.round(frame.player.hp)),ratio=clamp(hp/Math.max(1,frame.player.maxHp),0,1),key=`${frame.playerName}|${frame.playerLevel}|${hp}`;if(marker.lastKey===key)return;marker.lastKey=key;const ctx=marker.canvas.getContext("2d");if(!ctx)return;ctx.clearRect(0,0,512,104);ctx.textAlign="center";ctx.shadowColor="rgba(0,0,0,.9)";ctx.shadowBlur=7;ctx.fillStyle="#fff4d3";ctx.font="800 26px Georgia,serif";ctx.fillText(frame.playerName,256,30);ctx.shadowBlur=0;ctx.fillStyle="rgba(220,236,240,.9)";ctx.font="600 18px system-ui";ctx.fillText(`LV ${frame.playerLevel}`,256,50);ctx.fillStyle="rgba(3,17,22,.9)";ctx.fillRect(118,58,276,16);ctx.strokeStyle="rgba(240,211,129,.78)";ctx.lineWidth=2;ctx.strokeRect(118,58,276,16);const hpGradient=ctx.createLinearGradient(121,0,391,0);hpGradient.addColorStop(0,"#2f9d49");hpGradient.addColorStop(1,"#75e66b");ctx.fillStyle=hpGradient;ctx.fillRect(121,61,270*ratio,10);marker.texture.needsUpdate=true;}

type IslandMarker = { sprite:THREE.Sprite;canvas:HTMLCanvasElement;texture:THREE.CanvasTexture;lastKey:string };
function createIslandMarker(){const canvas=document.createElement("canvas");canvas.width=360;canvas.height=72;const texture=new THREE.CanvasTexture(canvas);texture.colorSpace=THREE.SRGBColorSpace;texture.minFilter=THREE.LinearFilter;const material=new THREE.SpriteMaterial({map:texture,transparent:true,depthTest:false,depthWrite:false});const sprite=new THREE.Sprite(material);sprite.renderOrder=70;sprite.scale.set(118,24,1);return {sprite,canvas,texture,lastKey:""};}
function paintIslandMarker(marker:IslandMarker,name:string,level:number){const key=`${name}|${level}`;if(marker.lastKey===key)return;marker.lastKey=key;const ctx=marker.canvas.getContext("2d");if(!ctx)return;ctx.clearRect(0,0,360,72);ctx.textAlign="center";ctx.shadowColor="rgba(0,0,0,.85)";ctx.shadowBlur=6;ctx.fillStyle="#e8f6f8";ctx.font="700 17px system-ui";ctx.fillText(name,180,28);ctx.shadowBlur=0;ctx.fillStyle="rgba(180,220,228,.88)";ctx.font="600 14px system-ui";ctx.fillText(`LV ${level}`,180,48);marker.texture.needsUpdate=true;}

function createImpactEffect(monster=false){const root=new THREE.Group(),flash=new THREE.PointLight(monster?0x6fffee:0xff9c4d,6,170);flash.position.y=30;root.add(flash);for(let i=0;i<9;i++){const smoke=new THREE.Mesh(new THREE.IcosahedronGeometry(3.8+i%3,1),new THREE.MeshStandardMaterial({color:i<3?0xffb05d:0x6e7777,transparent:true,opacity:.72,roughness:1}));smoke.position.set((i%3-1)*8,20+Math.floor(i/3)*8,(Math.sin(i*2.1))*10);smoke.userData.velocity=new THREE.Vector3((i%3-1)*5,14+i*1.8,Math.sin(i*2.1)*5);root.add(smoke);}const splash=new THREE.Mesh(new THREE.RingGeometry(10,14,28),new THREE.MeshBasicMaterial({color:0xd9ffff,transparent:true,opacity:.75,side:THREE.DoubleSide,depthWrite:false}));splash.rotation.x=-Math.PI/2;splash.position.y=2;root.add(splash);return root;}

function islandContour(rx:number,ry:number,seed:number,scale=1){
  const points:THREE.Vector2[]=[];
  for(let i=0;i<40;i++){const a=i/40*Math.PI*2,rough=1+Math.sin(a*3+seed)*.08+Math.sin(a*7-seed*.7)*.045+Math.cos(a*11+seed)*.025;points.push(new THREE.Vector2(Math.cos(a)*rx*rough*scale,Math.sin(a)*ry*rough*scale));}
  return points;
}

function createIslandPresentation(isle:{rx:number;ry:number;port?:boolean},texture:THREE.Texture,seed:number,kind:"tropical"|"storm"|"abyss"){
  const root=new THREE.Group(),coast=islandContour(isle.rx,isle.ry,seed,1.015);
  const foamPoints=coast.map(p=>new THREE.Vector3(p.x,.4,p.y)),foam=new THREE.LineLoop(new THREE.BufferGeometry().setFromPoints(foamPoints),new THREE.LineBasicMaterial({color:0xd8ffff,transparent:true,opacity:.38,depthWrite:false}));root.add(foam);
  const reefMaterial=new THREE.MeshBasicMaterial({color:kind==="abyss"?0x66598a:kind==="storm"?0x407a7c:0x76b49c,transparent:true,opacity:.16,depthWrite:false,side:THREE.DoubleSide});for(let i=0;i<5;i++){const reef=new THREE.Mesh(new THREE.CircleGeometry(13+(i%3)*7,18),reefMaterial);reef.rotation.x=-Math.PI/2;const a=seed*.71+i*1.37,r=isle.rx*(1.02+(i%2)*.11);reef.position.set(Math.cos(a)*r,-1.2,Math.sin(a)*r*isle.ry/isle.rx);reef.scale.set(1.45,.72,1);root.add(reef);}
  const shadowShape=new THREE.Shape(islandContour(isle.rx,isle.ry,seed,.91)),shadow=new THREE.Mesh(new THREE.ShapeGeometry(shadowShape),new THREE.MeshBasicMaterial({color:0x001015,transparent:true,opacity:.24,depthWrite:false,side:THREE.DoubleSide}));shadow.rotation.x=-Math.PI/2;shadow.position.set(10,-.2,14);root.add(shadow);
  const material=new THREE.SpriteMaterial({map:texture,transparent:true,alphaTest:.035,depthTest:true,depthWrite:false,sizeAttenuation:true,toneMapped:true});material.rotation=(seed%3-1)*.018;const sprite=new THREE.Sprite(material);sprite.center.set(.5,.2);sprite.renderOrder=6;const baseWidth=isle.rx*1.5*(isle.port?1.08:.96),baseHeight=baseWidth*(kind==="abyss"?.82:.69);sprite.scale.set(seed%2?-baseWidth:baseWidth,baseHeight,1);sprite.position.y=8;root.add(sprite);
  const rockMaterial=mat(kind==="abyss"?0x31324b:kind==="storm"?0x384a4d:0x59604f,.92,.02);for(let i=0;i<10;i++){const a=i/10*Math.PI*2+seed*.37,r=isle.rx*(.82+(i%3)*.07),rock=new THREE.Mesh(new THREE.DodecahedronGeometry(8+(i%4)*2.3,0),rockMaterial);rock.scale.set(1,.65+(i%2)*.2,.8);rock.position.set(Math.cos(a)*r,2,Math.sin(a)*isle.ry/isle.rx*r);rock.rotation.set(i*.17,a,i*.11);root.add(rock);}
  if(isle.port){const harborGlow=new THREE.PointLight(0xffb65b,3.2,isle.rx*1.55);harborGlow.position.set(0,65,0);root.add(harborGlow);}
  return root;
}

function createLootChest(){const root=new THREE.Group(),wood=mat(0x8a5228,.62,.08),metal=mat(0xd9a23f,.34,.72),base=new THREE.Mesh(new THREE.BoxGeometry(24,12,18),wood);base.position.y=8;root.add(base);const lid=new THREE.Mesh(new THREE.CylinderGeometry(9,9,24,16,1,false,0,Math.PI),wood);lid.rotation.z=Math.PI/2;lid.rotation.y=Math.PI/2;lid.position.y=14;root.add(lid);for(const x of [-8,8]){const band=new THREE.Mesh(new THREE.BoxGeometry(3,17,19),metal);band.position.set(x,11,0);root.add(band);}const lock=new THREE.Mesh(new THREE.BoxGeometry(5,7,2.5),metal);lock.position.set(0,10,10);root.add(lock);const aura=new THREE.PointLight(0xffc446,3.2,110);aura.position.y=24;root.add(aura);const halo=new THREE.Mesh(new THREE.RingGeometry(18,22,30),new THREE.MeshBasicMaterial({color:0xffcf55,transparent:true,opacity:.32,side:THREE.DoubleSide,depthWrite:false}));halo.rotation.x=-Math.PI/2;halo.position.y=1;root.add(halo);return root;}

const seeded=(seed:number)=>{const x=Math.sin(seed*91.731)*43758.5453;return x-Math.floor(x);};
type PropKind="rock"|"reef"|"buoy"|"crate"|"barrel"|"driftwood"|"wreck"|"mast"|"pier"|"ruin";
function createWorldProp(kind:PropKind,seed:number){
  const root=new THREE.Group(),darkWood=mat(0x4b2d1c,.9,.03),wood=mat(0x78502f,.82,.04),bronze=mat(0xa87333,.42,.62),rope=mat(0x9b845c,.98,.01),rock=mat(kind==="reef"?0x4f685f:0x4d5351,.92,.04),stone=mat(0x64645d,.95,.03);
  if(kind==="rock"||kind==="reef"){const count=kind==="reef"?3:2;for(let i=0;i<count;i++){const mesh=new THREE.Mesh(new THREE.DodecahedronGeometry(7+seeded(seed+i)*9,1),rock);mesh.scale.set(.8+seeded(seed+i+4)*.7,.55+seeded(seed+i+8)*.75,.8+seeded(seed+i+12)*.5);mesh.position.set((i-1)*8,mesh.scale.y*5,(seeded(seed+i+15)-.5)*8);mesh.rotation.set(seed*.13+i*.4,seed*.21+i,seed*.08);root.add(mesh);}}
  else if(kind==="buoy"){const body=new THREE.Mesh(new THREE.SphereGeometry(7,12,9),mat(0x943e31,.62,.18)),collar=new THREE.Mesh(new THREE.TorusGeometry(7,1.4,6,16),rope),mast=new THREE.Mesh(new THREE.CylinderGeometry(.9,1.2,19,8),darkWood),cap=new THREE.Mesh(new THREE.ConeGeometry(3.2,7,6),bronze);body.position.y=5;collar.rotation.x=Math.PI/2;collar.position.y=5;mast.position.y=15;cap.position.y=27;root.add(body,collar,mast,cap);}
  else if(kind==="crate"){const box=new THREE.Mesh(new THREE.BoxGeometry(18,14,16),wood);box.position.y=8;root.add(box);for(const axis of [-1,1]){const band=new THREE.Mesh(new THREE.BoxGeometry(2.2,16,17),darkWood);band.position.set(axis*5,8,0);root.add(band);}}
  else if(kind==="barrel"){const barrel=new THREE.Mesh(new THREE.CylinderGeometry(7,7.8,16,12),wood);barrel.position.y=8;for(const y of [3,8,13]){const band=new THREE.Mesh(new THREE.TorusGeometry(7.45,.7,6,16),bronze);band.rotation.x=Math.PI/2;band.position.y=y;root.add(band);}root.add(barrel);}
  else if(kind==="driftwood"){for(let i=0;i<3;i++){const log=new THREE.Mesh(new THREE.CylinderGeometry(1.5,2.2,30-i*5,7),i?wood:darkWood);log.rotation.z=Math.PI/2+(i-1)*.17;log.rotation.y=(i-1)*.35;log.position.set((i-1)*5,2,(i-1)*4);root.add(log);}}
  else if(kind==="wreck"||kind==="mast"){const beamCount=kind==="wreck"?5:2;for(let i=0;i<beamCount;i++){const beam=new THREE.Mesh(new THREE.BoxGeometry(31-i*2,3.4,5),i%2?wood:darkWood);beam.position.set((i-2)*5,3+i*.4,(i-2)*4);beam.rotation.y=-.55+i*.23;beam.rotation.z=(i-2)*.05;root.add(beam);}const mast=new THREE.Mesh(new THREE.CylinderGeometry(1.8,2.5,kind==="wreck"?44:58,8),darkWood);mast.rotation.z=1.12;mast.position.set(4,8,-3);root.add(mast);}
  else if(kind==="pier"){for(let i=0;i<5;i++){const plank=new THREE.Mesh(new THREE.BoxGeometry(15,2.2,7),wood);plank.position.set(i*13,7,0);root.add(plank);for(const z of [-5,5]){const post=new THREE.Mesh(new THREE.CylinderGeometry(1.5,2,18,7),darkWood);post.position.set(i*13,1,z);root.add(post);}}}
  else {for(let i=0;i<3;i++){const column=new THREE.Mesh(new THREE.CylinderGeometry(4.2,5.2,18+i*5,7),stone);column.position.set((i-1)*11,(18+i*5)/2,0);column.rotation.z=(i-1)*.05;root.add(column);}const cap=new THREE.Mesh(new THREE.BoxGeometry(36,4,10),stone);cap.position.set(0,24,0);cap.rotation.z=.06;root.add(cap);}
  root.userData.worldProp=kind;return shadows(root);
}

function createWaterSplash(color=0xd7fbff){const root=new THREE.Group(),ring=new THREE.Mesh(new THREE.RingGeometry(7,11,26),new THREE.MeshBasicMaterial({color,transparent:true,opacity:.72,side:THREE.DoubleSide,depthWrite:false}));ring.rotation.x=-Math.PI/2;ring.position.y=1;root.add(ring);for(let i=0;i<8;i++){const drop=new THREE.Mesh(new THREE.ConeGeometry(1.5,8+seeded(i)*7,5),new THREE.MeshBasicMaterial({color,transparent:true,opacity:.78,depthWrite:false}));const a=i/8*Math.PI*2;drop.position.set(Math.cos(a)*8,6+seeded(i+3)*7,Math.sin(a)*8);drop.rotation.z=(seeded(i+8)-.5)*.7;drop.userData.velocity=new THREE.Vector3(Math.cos(a)*(8+seeded(i)*7),16+seeded(i+6)*10,Math.sin(a)*(8+seeded(i+2)*7));root.add(drop);}return root;}

function createMuzzleEffect(color:number|THREE.Color){const root=new THREE.Group(),flash=new THREE.PointLight(color,5.2,100);flash.position.y=12;root.add(flash);const flare=new THREE.Mesh(new THREE.SphereGeometry(5.5,10,8),new THREE.MeshBasicMaterial({color,transparent:true,opacity:.9,depthWrite:false}));flare.position.y=12;root.add(flare);for(let i=0;i<4;i++){const smoke=new THREE.Mesh(new THREE.IcosahedronGeometry(3.5+i*.6,1),new THREE.MeshStandardMaterial({color:0x879091,transparent:true,opacity:.5,roughness:1}));smoke.position.set(-i*3,12+i*3,(i-1.5)*2);smoke.userData.velocity=new THREE.Vector3(-5-i*2,8+i*2,(i-1.5)*2);root.add(smoke);}return root;}

function createWakePatch(strength:number){const root=new THREE.Group(),foam=new THREE.MeshBasicMaterial({color:0xb8e8f0,transparent:true,opacity:.07+.16*strength,depthWrite:false,side:THREE.DoubleSide,blending:THREE.AdditiveBlending});for(const side of [-1,1]){const curve=new THREE.CatmullRomCurve3([new THREE.Vector3(-4,.35,side*2),new THREE.Vector3(-16,.28,side*(4+strength*2)),new THREE.Vector3(-32-strength*12,.2,side*(6+strength*4))]),line=new THREE.Mesh(new THREE.TubeGeometry(curve,8,.42+strength*.22,4,false),foam.clone());root.add(line);}const ripple=new THREE.Mesh(new THREE.RingGeometry(6+strength*3,8+strength*4,20),foam.clone());ripple.rotation.x=-Math.PI/2;ripple.position.x=-14;ripple.position.y=.15;root.add(ripple);return root;}

function tuneImportedMaterial(material:THREE.Material,maxAnisotropy:number){
  const tuned=material.clone();
  if(tuned instanceof THREE.MeshStandardMaterial){
    tuned.metalness=Math.min(tuned.metalness,.48);tuned.roughness=Math.max(tuned.roughness,.72);tuned.envMapIntensity=.88;
    const hsl={h:0,s:0,l:0};tuned.color.getHSL(hsl);
    if(hsl.l<.28){tuned.emissive=tuned.emissive?.clone()??tuned.color.clone();tuned.emissiveIntensity=Math.max(tuned.emissiveIntensity,.07);}
    for(const texture of [tuned.map,tuned.metalnessMap,tuned.roughnessMap,tuned.normalMap,tuned.emissiveMap])if(texture){texture.anisotropy=Math.min(8,maxAnisotropy);texture.minFilter=THREE.LinearMipmapLinearFilter;texture.magFilter=THREE.LinearFilter;texture.generateMipmaps=true;texture.needsUpdate=true;}
    if(tuned.map)tuned.map.colorSpace=THREE.SRGBColorSpace;
  }
  return tuned;
}

function createShipVisualDebug(visual:THREE.Object3D,definition:ShipVisualDefinition){
  const root=new THREE.Group();root.name="ShipVisualDebug";root.add(new THREE.Box3Helper(new THREE.Box3().setFromObject(visual),0xffd15c),new THREE.AxesHelper(65));
  const markerMaterial=new THREE.MeshBasicMaterial({color:0x53f4e5,depthTest:false}),waterline=new THREE.Mesh(new THREE.RingGeometry(34,35,48),new THREE.MeshBasicMaterial({color:0x58ddff,transparent:true,opacity:.8,side:THREE.DoubleSide,depthTest:false}));waterline.rotation.x=-Math.PI/2;root.add(waterline);
  const addMarker=(name:string,forward:number,lateral:number,height:number,color:number)=>{const marker=new THREE.Mesh(new THREE.SphereGeometry(2.2,8,6),markerMaterial.clone());(marker.material as THREE.MeshBasicMaterial).color.setHex(color);marker.name=name;marker.position.set(forward,height,lateral);root.add(marker);};
  addMarker("WakeOrigin",definition.wakeOffset.forward,definition.wakeOffset.lateral,1,0x54e7ff);for(const [index,p] of definition.cannonOffsets.port.entries())addMarker(`Port_${index}`,p.forward,p.lateral,p.height,0xffd15c);for(const [index,p] of definition.cannonOffsets.starboard.entries())addMarker(`Starboard_${index}`,p.forward,p.lateral,p.height,0xff765c);return root;
}

export class AbyssalThreeRenderer {
  private renderer:THREE.WebGLRenderer; private scene=new THREE.Scene(); private camera=new THREE.PerspectiveCamera(GAMEPLAY_CAMERA_POLICY.fieldOfViewDegrees,1,2,6500);
  private quality:QualityProfile;
  private world=new THREE.Group(); private ocean!:THREE.Mesh; private player=new THREE.Group(); private playerVisualRoot=new THREE.Group(); private playerMarker=createPlayerMarker(); private playerAura=new THREE.Group(); private playerShipId:ShipId="sovereign"; private playerDeckLevel=1; private entityMeshes=new Map<number,THREE.Group>(); private entityBars=new Map<number,HealthMarker>(); private shotMeshes=new Map<Shot3D,THREE.Group>(); private wakeMeshes=new Map<Wake3D,THREE.Group>(); private lootMeshes=new Map<number,THREE.Group>(); private sinkingMeshes=new Map<number,{mesh:THREE.Group;start:number}>(); private lastHitSeen=new Map<number,number>(); private playerHitSeen=0; private impactMeshes:Array<{root:THREE.Group;start:number;duration?:number}>=[];
  private ring=new THREE.Mesh(new THREE.RingGeometry(54,60,56),new THREE.MeshBasicMaterial({color:0xffd76f,transparent:true,opacity:.68,side:THREE.DoubleSide,depthWrite:false}));
  private destinationRing=new THREE.Mesh(new THREE.RingGeometry(10,14,32),new THREE.MeshBasicMaterial({color:0xffdf78,transparent:true,opacity:.85,side:THREE.DoubleSide,depthWrite:false}));
  private raycaster=new THREE.Raycaster(); private pointer=new THREE.Vector2(); private waterUniforms={uTime:{value:0},uDeep:{value:new THREE.Color(0x032f3f)},uShallow:{value:new THREE.Color(0x0a5f72)},uIslandCount:{value:0},uIslands:{value:Array.from({length:8},()=>new THREE.Vector4())}}; private mapId:MapId|null=null; private smoothedZoom=1;
  private cameraShakeStrength=0; private cameraShakeUntil=0; private playerVisualTemplates=new Map<ShipId,THREE.Group>(); private islandMarkers:IslandMarker[]=[]; private islandMarkerLevel=1; private lastKrakenPlacementProof="";

  constructor(private canvas:HTMLCanvasElement,qualityPreference:QualityPreference="AUTO"){
    this.quality=resolveQuality(qualityPreference);this.renderer=new THREE.WebGLRenderer({canvas,antialias:this.quality.id!=="LOW",alpha:false,powerPreference:"high-performance"});this.renderer.setPixelRatio(Math.min(devicePixelRatio*this.quality.renderScale,1.8));this.renderer.shadowMap.enabled=this.quality.shadows;this.renderer.shadowMap.type=THREE.PCFSoftShadowMap;this.renderer.outputColorSpace=THREE.SRGBColorSpace;this.renderer.toneMapping=THREE.ACESFilmicToneMapping;this.renderer.toneMappingExposure=1.48;
    this.scene.background=new THREE.Color(0x2a9cbd);this.scene.fog=new THREE.FogExp2(0x2a9cbd,.00011);this.scene.add(this.world);
    this.scene.add(new THREE.AmbientLight(0xfff4dc,.95));this.scene.add(new THREE.HemisphereLight(0xe9fbff,0x7a9068,2.85));const sun=new THREE.DirectionalLight(0xffe8b8,3.9);sun.position.set(-700,1100,-480);sun.castShadow=this.quality.shadows;sun.shadow.mapSize.set(this.quality.shadowMapSize,this.quality.shadowMapSize);sun.shadow.camera.left=-1300;sun.shadow.camera.right=1300;sun.shadow.camera.top=1100;sun.shadow.camera.bottom=-1100;this.scene.add(sun);
    const rim=new THREE.DirectionalLight(0x6ae4ff,1.48);rim.position.set(900,420,700);this.scene.add(rim);
    this.player.name="PlayerShipRoot";this.playerVisualRoot.name="PlayerShipVisualRoot";const initialFallback=createShip("player");initialFallback.name="ProceduralPlayerFallback";initialFallback.userData.visualFallback=true;this.playerVisualRoot.add(initialFallback);this.player.add(this.playerVisualRoot);this.player.userData.player=true;const auraRing=new THREE.Mesh(new THREE.RingGeometry(55,60,64),new THREE.MeshBasicMaterial({color:0x52f1e5,transparent:true,opacity:.12,side:THREE.DoubleSide,depthWrite:false,blending:THREE.AdditiveBlending}));auraRing.rotation.x=-Math.PI/2;auraRing.userData.auraRing=true;const auraLight=new THREE.PointLight(0x54e4df,.85,140);auraLight.position.y=30;auraLight.userData.auraLight=true;this.playerAura.add(auraRing,auraLight);this.world.add(this.player,this.playerMarker.sprite,this.playerAura);this.ring.rotation.x=-Math.PI/2;this.ring.position.y=3;this.ring.visible=false;this.world.add(this.ring);this.destinationRing.rotation.x=-Math.PI/2;this.destinationRing.position.y=3;this.destinationRing.visible=false;this.world.add(this.destinationRing);
    this.setMap("aster");this.loadPlayerShipVisuals();
  }

  private publishPlayerVisualState(state:PlayerVisualRuntimeState){this.player.userData.visualRuntimeState=state;if(typeof window!=="undefined"){(window as Window&{__ABYSSAL_PLAYER_VISUAL__?:PlayerVisualRuntimeState}).__ABYSSAL_PLAYER_VISUAL__=state;window.dispatchEvent(new CustomEvent("abyssal:player-visual-status",{detail:state}));}}
  private inspectPlayerVisual(status:PlayerVisualRuntimeState["status"],visualId:string,assetUrl?:string,error?:string){const krakenMesh=this.playerVisualRoot.getObjectByName("ImportedKrakenMesh");let meshCount=0,fallbackPresent=false;krakenMesh?.traverse(o=>{if(o instanceof THREE.Mesh)meshCount++;});this.playerVisualRoot.traverse(o=>{if(o.userData.visualFallback)fallbackPresent=true;});this.player.updateMatrixWorld(true);const size=new THREE.Vector3(),center=new THREE.Vector3(),playerPosition=new THREE.Vector3(),box=new THREE.Box3().setFromObject(this.playerVisualRoot);this.player.getWorldPosition(playerPosition);if(!box.isEmpty()){box.getSize(size);box.getCenter(center);}return{status,visualId,assetUrl,meshCount,krakenMeshAttached:!!krakenMesh,fallbackPresent,playerRootAttached:this.player.parent===this.world,visualRootAttached:this.playerVisualRoot.parent===this.player,activeShipId:this.playerShipId,sceneGraph:{playerRoot:this.player.name,visualRoot:this.playerVisualRoot.name,children:this.playerVisualRoot.children.map(child=>child.name||child.type)},bounds:box.isEmpty()?undefined:{x:size.x,y:size.y,z:size.z},playerWorldPosition:{x:playerPosition.x,y:playerPosition.y,z:playerPosition.z},visualBoundsCenter:box.isEmpty()?undefined:{x:center.x,y:center.y,z:center.z},error} satisfies PlayerVisualRuntimeState;}
  private attachPlayerVisual(visual:THREE.Group,visualId:string){this.playerVisualRoot.clear();visual.visible=true;visual.userData.visualFallback=false;this.playerVisualRoot.add(visual);const proof=this.inspectPlayerVisual("kraken-attached",visualId);if(proof.meshCount<1||!proof.krakenMeshAttached||proof.fallbackPresent||!proof.playerRootAttached||!proof.visualRootAttached||!proof.bounds||Math.max(proof.bounds.x,proof.bounds.y,proof.bounds.z)<=0){throw new Error(`Player visual scene-graph verification failed: ${JSON.stringify(proof)}`);}this.publishPlayerVisualState(proof);console.info("[Abyssal][PlayerVisual] Kraken GLB loaded -> mesh attached -> fallback hidden",proof);}
  private createConfiguredPlayerVisual(source:THREE.Group,definition:ShipVisualDefinition){const root=new THREE.Group(),visual=source.clone(true),maxAnisotropy=this.renderer.capabilities.getMaxAnisotropy();root.name=`ShipVisual_${definition.id}`;visual.name="ImportedKrakenMesh";visual.scale.setScalar(definition.scale);visual.rotation.y=definition.rotationOffsetY;visual.position.y=definition.waterlineOffset;visual.visible=true;visual.traverse(o=>{o.visible=true;if(o instanceof THREE.Mesh){o.castShadow=definition.shadow.cast;o.receiveShadow=definition.shadow.receive;o.frustumCulled=false;o.material=Array.isArray(o.material)?o.material.map(m=>tuneImportedMaterial(m,maxAnisotropy)):tuneImportedMaterial(o.material,maxAnisotropy);}});root.add(visual,createHullWaterInteraction(96,33,true));root.userData.entityRoot=true;root.userData.baseScale=1;root.userData.visualDefinitionId=definition.id;const localDebug=typeof location!=="undefined"&&(location.hostname==="localhost"||location.hostname==="127.0.0.1")&&new URLSearchParams(location.search).get("shipDebug")==="1";if(localDebug)root.add(createShipVisualDebug(visual,definition));return root;}
  private resolveAssetUrls(assetPath:string){const normalized=assetPath.replace(/^\/+/,""),base=typeof document!=="undefined"?new URL("./",document.baseURI):new URL("http://localhost/"),origin=typeof location!=="undefined"?new URL("/",location.origin):base,urls=[new URL(normalized,base),new URL(normalized,origin)];for(const url of urls)url.searchParams.set("v","20.1-kraken-device-fix-3");return [...new Set(urls.map(url=>url.href))];}
  private async loadGlbScene(loader:GLTFLoader,assetPath:string){const candidates=this.resolveAssetUrls(assetPath),requestErrors:string[]=[];for(const assetUrl of candidates){this.publishPlayerVisualState(this.inspectPlayerVisual("loading","kraken-player-30k",assetUrl));console.info("[Abyssal][PlayerVisual] Loading Kraken GLB",{assetUrl});let response:Response;try{response=await fetch(assetUrl,{cache:"no-store"});}catch(error){requestErrors.push(`${assetUrl}: ${error instanceof Error?error.message:String(error)}`);continue;}if(!response.ok){requestErrors.push(`${assetUrl}: HTTP ${response.status} ${response.statusText}`);continue;}const buffer=await response.arrayBuffer(),header=new Uint8Array(buffer,0,Math.min(4,buffer.byteLength));if(buffer.byteLength<20||String.fromCharCode(...header)!=="glTF")throw new Error(`Kraken GLB response is invalid (${buffer.byteLength} bytes) at ${assetUrl}`);const basePath=assetUrl.slice(0,assetUrl.lastIndexOf("/")+1);try{const gltf=await loader.parseAsync(buffer,basePath);return{scene:gltf.scene,assetUrl,bytes:buffer.byteLength};}catch(error){throw new Error(`Kraken GLB parse/material failed at ${assetUrl}: ${error instanceof Error?error.message:String(error)}`);}}throw new Error(`Kraken GLB request failed: ${requestErrors.join(" | ")||"no asset URL resolved"}`);}
  private async loadLegacySovereignVisual(loader:GLTFLoader){try{const load=(url:string)=>loader.loadAsync(url),[lod0,lod1,lod2]=await Promise.all([load("/assets/3d/ships/sovereign-frigate/sovereign-frigate-lod0.glb"),load("/assets/3d/ships/sovereign-frigate/sovereign-frigate-lod1.glb"),load("/assets/3d/ships/sovereign-frigate/sovereign-frigate-lod2.glb")]),lod=new THREE.LOD(),root=new THREE.Group();lod.name="Sovereign_Frigate_LOD_Set";lod.addLevel(lod0.scene,0);lod.addLevel(lod1.scene,700*this.quality.lodBias);lod.addLevel(lod2.scene,1200*this.quality.lodBias);root.name="Sovereign_Frigate_V20_Fallback";root.add(lod,createHullWaterInteraction(102,20));root.userData.entityRoot=true;root.userData.baseScale=SHIP_MAP_SCALE;root.userData.visualFallback=true;root.scale.setScalar(SHIP_MAP_SCALE);this.playerVisualTemplates.set("sovereign",root);if(this.playerShipId==="sovereign"){this.playerVisualRoot.clear();this.playerVisualRoot.add(root.clone(true));}this.publishPlayerVisualState(this.inspectPlayerVisual("fallback","sovereign-frigate-v20-fallback"));}catch(error){const message=error instanceof Error?error.message:String(error);console.error("[Abyssal][PlayerVisual] Imported fallback failed; procedural ship remains active.",error);this.publishPlayerVisualState(this.inspectPlayerVisual("kraken-failed","procedural-player-fallback",undefined,message));}}
  private async loadPlayerShipVisuals(){const loader=new GLTFLoader(),definition=PLAYER_SHIP_VISUALS[this.playerShipId];if(!definition||!validateShipVisualDefinition(definition)){await this.loadLegacySovereignVisual(loader);return;}try{const loaded=await this.loadGlbScene(loader,definition.assetPath),root=this.createConfiguredPlayerVisual(loaded.scene,definition);for(const shipId of PLAYER_SHIP_IDS)this.playerVisualTemplates.set(shipId,root);this.attachPlayerVisual(root.clone(true),definition.id);console.info("[Abyssal][PlayerVisual] Kraken assigned to active saved player ship",{shipId:this.playerShipId,bytes:loaded.bytes,assetUrl:loaded.assetUrl});}catch(error){const message=error instanceof Error?error.message:String(error);console.error("[Abyssal][PlayerVisual] Kraken load/attach failed; keeping fallback.",{error:message,sceneGraph:this.inspectPlayerVisual("kraken-failed",definition.id,definition.assetPath,message)});await this.loadLegacySovereignVisual(loader);this.publishPlayerVisualState(this.inspectPlayerVisual("kraken-failed",definition.id,definition.assetPath,message));}}

  private createOcean(){
    const segments=this.quality.waterSegments,geo=new THREE.PlaneGeometry(7200,5200,segments,Math.round(segments*.75));const material=new THREE.ShaderMaterial({uniforms:this.waterUniforms,vertexShader:`uniform float uTime;varying float vWave;varying vec3 vWorld;void main(){vec3 p=position;float a=sin(p.x*.009+uTime*.55)*.72;float b=sin(p.y*.013-uTime*.42)*.48;float c=sin((p.x*.7+p.y)*.026+uTime*.83)*.22;p.z+=(a+b+c)*1.25;vWave=a+b+c;vec4 wp=modelMatrix*vec4(p,1.);vWorld=wp.xyz;gl_Position=projectionMatrix*viewMatrix*wp;}`,fragmentShader:`uniform float uTime;uniform vec3 uDeep;uniform vec3 uShallow;uniform int uIslandCount;uniform vec4 uIslands[8];varying float vWave;varying vec3 vWorld;float hash(vec2 p){return fract(sin(dot(p,vec2(127.1,311.7)))*43758.5453);}float noise(vec2 p){vec2 i=floor(p),f=fract(p);f=f*f*(3.-2.*f);return mix(mix(hash(i),hash(i+vec2(1.,0.)),f.x),mix(hash(i+vec2(0.,1.)),hash(i+vec2(1.,1.)),f.x),f.y);}float fbm(vec2 p){float v=0.;v+=noise(p)*.58;p=p*2.07+4.1;v+=noise(p)*.28;p=p*2.03-2.4;v+=noise(p)*.14;return v;}void main(){vec2 flow=vWorld.xz*.0065+vec2(uTime*.027,-uTime*.018);float body=fbm(flow),detail=fbm(flow*4.8+vec2(-uTime*.05,uTime*.035));float coast=0.;float foam=0.;for(int i=0;i<8;i++){if(i>=uIslandCount)break;vec4 q=uIslands[i];vec2 d=(vWorld.xz-q.xy)/q.zw;float edge=length(d)+(noise(vWorld.xz*.021+float(i)*7.3)-.5)*.13;coast=max(coast,1.-smoothstep(.98,1.72,edge));foam=max(foam,1.-smoothstep(.035,.13,abs(edge-1.05)));}float crest=smoothstep(1.05,1.55,vWave+detail*.3)*.13;float glint=smoothstep(.88,.985,detail+vWave*.035)*.12;vec3 col=mix(uDeep,uShallow,.16+(body-.5)*.2+coast*.78+vWave*.018+detail*.08);col=mix(col,vec3(.12,.28,.42),smoothstep(.35,.92,body)*.22);col=mix(col,vec3(.7,.96,.94),glint+crest+foam*.36);gl_FragColor=vec4(col,1.);}`,side:THREE.DoubleSide});
    this.ocean=new THREE.Mesh(geo,material);this.ocean.rotation.x=-Math.PI/2;this.ocean.position.y=-4;this.ocean.receiveShadow=true;this.world.add(this.ocean);
  }

  setMap(id:MapId){
    if(this.mapId===id)return;this.mapId=id;const keep=new Set<THREE.Object3D>([this.player,this.playerMarker.sprite,this.playerAura,this.ring,this.destinationRing]);for(const child of [...this.world.children])if(!keep.has(child))this.world.remove(child);for(const marker of this.islandMarkers){this.world.remove(marker.sprite);marker.texture.dispose();marker.sprite.material.dispose();}this.islandMarkers=[];this.entityMeshes.clear();for(const marker of this.entityBars.values()){marker.texture.dispose();marker.sprite.material.dispose();}this.entityBars.clear();this.shotMeshes.clear();this.wakeMeshes.clear();this.lootMeshes.clear();this.sinkingMeshes.clear();this.impactMeshes=[];this.lastHitSeen.clear();this.createOcean();
    const map=MAPS[id],colors=map.color,shallow=new THREE.Color(colors[0]).offsetHSL(0,.08,.14),deep=new THREE.Color(colors[1]).offsetHSL(0,.04,.02);this.waterUniforms.uShallow.value.copy(shallow);this.waterUniforms.uDeep.value.copy(deep);this.waterUniforms.uIslandCount.value=Math.min(8,map.islands.length);for(let i=0;i<8;i++){const isle=map.islands[i];this.waterUniforms.uIslands.value[i].set(isle?.x??-9999,isle?.y??-9999,isle?.rx??1,isle?.ry??1);}const sky=map.weather==="void"?new THREE.Color(0x334c67):map.weather==="storm"?new THREE.Color(0x6a9aab):new THREE.Color(0x8ad4e0);this.scene.background=sky;this.scene.fog=new THREE.FogExp2(sky,map.weather==="void"?.00028:map.weather==="storm"?.0002:.00013);this.islandMarkerLevel=map.recommended;
    for(const [index,isle] of map.islands.entries()){
      const kind=id==="abyss"?"abyss":id==="gloam"||id==="maelstrom"?"storm":"tropical";
      const root=createIslandPresentation(isle,islandArtTextures[kind],index+1,kind);root.position.set(isle.x,2,isle.y);
      if(kind!=="tropical"){const light=new THREE.PointLight(kind==="abyss"?0xa35cff:0x57e2ec,isle.port?3.2:2.1,isle.rx*2.2);light.position.set(0,85,0);root.add(light);}
      this.world.add(root);
      const propKinds:PropKind[]=isle.port?["pier","buoy","crate","barrel","ruin"]:["rock","reef","driftwood","wreck","mast"];const propCount=this.quality.id==="LOW"?3:5;for(let p=0;p<propCount;p++){const propKind=propKinds[(p+index)%propKinds.length],prop=createWorldProp(propKind,index*31+p+3),a=index*.83+p*1.91,r=isle.rx*(1.05+.12*(p%3));prop.position.set(isle.x+Math.cos(a)*r,propKind==="reef"?-1:0,isle.y+Math.sin(a)*r*isle.ry/isle.rx);prop.rotation.y=a+seeded(index*17+p)*.5;prop.scale.setScalar(.8+seeded(index*13+p)*.45);this.world.add(prop);}
      if(isle.port||isle.rx>=185){const marker=createIslandMarker();paintIslandMarker(marker,isle.name,this.islandMarkerLevel);marker.sprite.position.set(isle.x,18,isle.y+isle.ry*.42);this.world.add(marker.sprite);this.islandMarkers.push(marker);}
    }
    const openKinds:PropKind[]=["crate","barrel","driftwood","wreck","buoy","mast","reef"];const openCount=this.quality.id==="LOW"?6:10;for(let i=0;i<openCount;i++){const prop=createWorldProp(openKinds[i%openKinds.length],91+i),x=map.width*(.14+seeded(i+81)*.72),z=map.height*(.12+seeded(i+121)*.76);if(map.islands.every(isle=>Math.hypot((x-isle.x)/isle.rx,(z-isle.y)/isle.ry)>1.55)){prop.position.set(x,0,z);prop.rotation.y=seeded(i+221)*Math.PI*2;prop.scale.setScalar(.65+seeded(i+301)*.38);this.world.add(prop);}}
  }

  private ensureEntity(e:Entity3D){let mesh=this.entityMeshes.get(e.id);if(!mesh){mesh=monsterKinds.has(e.kind)?createKraken(e.kind):createShip(e.kind);mesh.userData.entityId=e.id;mesh.traverse(o=>o.userData.entityId=e.id);this.entityMeshes.set(e.id,mesh);this.world.add(mesh);}return mesh;}
  private ensurePlayerShip(id:ShipId,deckLevel:number){if(this.playerShipId===id&&this.playerDeckLevel===deckLevel)return;this.playerShipId=id;this.playerDeckLevel=deckLevel;const template=this.playerVisualTemplates.get(id),visual=template?template.clone(true):createShip("player",id,deckLevel);if(!template){visual.name=`ProceduralPlayerFallback_${id}`;visual.userData.visualFallback=true;}this.playerVisualRoot.clear();this.playerVisualRoot.add(visual);this.lastKrakenPlacementProof="";const krakenActive=!!template&&!template.userData.visualFallback,visualId=(template?.userData.visualDefinitionId as string|undefined)??`procedural-${id}`,state=this.inspectPlayerVisual(krakenActive?"kraken-attached":"fallback",visualId);this.publishPlayerVisualState(state);}
  getPlayerVisualRuntimeState(){return this.inspectPlayerVisual((this.player.userData.visualRuntimeState as PlayerVisualRuntimeState|undefined)?.status??"fallback",(this.player.userData.visualRuntimeState as PlayerVisualRuntimeState|undefined)?.visualId??"unknown");}
  private playerMuzzlePosition(frame:WorldFrame,shot:Shot3D){const definition=PLAYER_SHIP_VISUALS[frame.shipId];if(!definition)return{x:shot.x,y:shot.y,height:4};const shotAngle=Math.atan2(shot.vy,shot.vx),side=Math.sin(shotAngle-frame.player.angle)>=0?"port":"starboard",points=definition.cannonOffsets[side],point=points[Math.floor(points.length/2)]??{forward:0,lateral:side==="port"?17:-17,height:10},cos=Math.cos(frame.player.angle),sin=Math.sin(frame.player.angle);return{x:frame.player.x+cos*point.forward-sin*point.lateral,y:frame.player.y+sin*point.forward+cos*point.lateral,height:point.height};}
  private requestCameraShake(strength:number,time:number,duration=190){this.cameraShakeStrength=Math.min(GAMEPLAY_CAMERA_POLICY.maxShake,Math.max(this.cameraShakeStrength,strength));this.cameraShakeUntil=Math.max(this.cameraShakeUntil,time+duration);}
  render(frame:WorldFrame,time:number){
    this.ensurePlayerShip(frame.shipId,frame.deckLevel);this.setMap(frame.mapId);this.waterUniforms.uTime.value=time*.001;this.smoothedZoom+=(frame.zoom-this.smoothedZoom)*.12;const boss=frame.entities.find(e=>e.id===frame.selectedId&&ENTITY_DATA[e.kind].boss),cameraRig=resolveCameraPresentation({zoom:this.smoothedZoom,mapId:frame.mapId,bossSelected:!!boss}),policy=GAMEPLAY_CAMERA_POLICY;
    // Fixed oblique 2.5D composition: world-space heading never follows ship rotation and no orbit input exists.
    const map=MAPS[frame.mapId],cameraCenterX=clamp(frame.player.x+frame.cameraPan.x,260,map.width-260),cameraCenterZ=clamp(frame.player.y+frame.cameraPan.y,190,map.height-190),shake=time<this.cameraShakeUntil?this.cameraShakeStrength*clamp((this.cameraShakeUntil-time)/190,0,1):0,shakeX=Math.sin(time*.091)*shake,shakeZ=Math.cos(time*.077)*shake*.7,target=new THREE.Vector3(cameraCenterX+policy.targetOffsetX,12,cameraCenterZ+policy.targetOffsetZ*cameraRig.overview),desired=new THREE.Vector3(cameraCenterX+cameraRig.backDistance*policy.fixedLateralRatio+shakeX,cameraRig.height,cameraCenterZ+cameraRig.backDistance+shakeZ);this.camera.position.lerp(desired,policy.followSmoothing);this.camera.lookAt(target);if(time>=this.cameraShakeUntil)this.cameraShakeStrength=0;
    this.player.position.set(frame.player.x,Math.sin(time*.002)*1.4,frame.player.y);this.player.rotation.set(Math.sin(time*.0017)*.012,-frame.player.angle,Math.sin(time*.0013)*.018);const currentVisualState=this.player.userData.visualRuntimeState as PlayerVisualRuntimeState|undefined,placementKey=currentVisualState?.status==="kraken-attached"?`${frame.shipId}:${currentVisualState.visualId}`:"";if(placementKey&&placementKey!==this.lastKrakenPlacementProof){this.lastKrakenPlacementProof=placementKey;const placementProof=this.inspectPlayerVisual("kraken-attached",currentVisualState!.visualId,currentVisualState!.assetUrl);this.publishPlayerVisualState(placementProof);console.info("[Abyssal][PlayerVisual] Kraken follows gameplay PlayerShipRoot",placementProof);}const interaction=(this.player.userData.waterInteraction as THREE.Group|undefined)??this.player.getObjectByName("HullWaterInteraction");if(interaction)interaction.traverse(o=>{if(o instanceof THREE.Mesh){const m=o.material as THREE.MeshBasicMaterial;m.opacity=.06+clamp(frame.player.speed/150,0,1)*.18;}});paintPlayerMarker(this.playerMarker,frame);const markerScale=clamp(1/this.smoothedZoom,.78,1.22);this.playerMarker.sprite.scale.set(132*markerScale,30*markerScale,1);this.playerMarker.sprite.position.set(frame.player.x,10,frame.player.y+50);this.playerAura.position.set(frame.player.x,3,frame.player.y);this.playerAura.rotation.y=time*.00008;const auraScale=1+Math.sin(time*.0032)*.015,speedFactor=clamp(Math.abs(frame.player.speed)/120,0,1);this.playerAura.scale.setScalar(auraScale);this.playerAura.visible=speedFactor>.08;const auraColor=frame.shipId==="ironclad"?0xff7a45:frame.shipId==="arcanum"?0xb27aff:frame.shipId==="tempest"?0x45f7e8:0xf0ca61;this.playerAura.traverse(o=>{if(o instanceof THREE.Mesh&&(o.material as THREE.MeshBasicMaterial).color)(o.material as THREE.MeshBasicMaterial).color.setHex(auraColor);if(o instanceof THREE.Mesh)(o.material as THREE.MeshBasicMaterial).opacity=.08+speedFactor*.1;if(o instanceof THREE.PointLight){o.color.setHex(auraColor);o.intensity=.45+speedFactor*.55;}});
    if(frame.lastHit>0&&frame.lastHit!==this.playerHitSeen){this.playerHitSeen=frame.lastHit;const root=createImpactEffect(false);root.position.set(frame.player.x,0,frame.player.y);this.world.add(root);this.impactMeshes.push({root,start:time});this.requestCameraShake(2.4,time,230);}
    const live=new Set<number>();
    for(const e of frame.entities){
      if(e.hp<=0)continue;live.add(e.id);const mesh=this.ensureEntity(e);mesh.visible=true;mesh.position.set(e.x,monsterKinds.has(e.kind)?Math.sin(time*.0018+e.id)*3:0,e.y);mesh.rotation.set(0,-e.angle,monsterKinds.has(e.kind)?Math.sin(time*.0016+e.id)*.016:0);const baseScale=(mesh.userData.baseScale as number|undefined)??1,scale=baseScale*(e.hitAt>performance.now()-120?1.08:1);mesh.scale.lerp(new THREE.Vector3(scale,scale,scale),.25);
      if(e.hitAt>0&&this.lastHitSeen.get(e.id)!==e.hitAt){this.lastHitSeen.set(e.id,e.hitAt);const root=createImpactEffect(monsterKinds.has(e.kind));root.position.set(e.x,0,e.y);this.world.add(root);this.impactMeshes.push({root,start:time});if(frame.selectedId===e.id||ENTITY_DATA[e.kind].boss)this.requestCameraShake(ENTITY_DATA[e.kind].boss?4.5:1.8,time);}
      let marker=this.entityBars.get(e.id);if(!marker){marker=createHealthMarker(e);this.entityBars.set(e.id,marker);this.world.add(marker.sprite);}const selected=frame.selectedId===e.id;paintHealthMarker(marker,e,selected);const compact=clamp(1/this.smoothedZoom,.78,1.18);marker.sprite.scale.set((selected?118:100)*compact,(selected?30:26)*compact,1);marker.sprite.position.set(e.x,10,e.y+34);marker.sprite.visible=true;
    }
    for(const [id,mesh] of this.entityMeshes)if(!live.has(id)){const destroyed=frame.entities.some(e=>e.id===id&&e.hp<=0);this.entityMeshes.delete(id);if(destroyed){this.sinkingMeshes.set(id,{mesh,start:time});}else this.world.remove(mesh);const marker=this.entityBars.get(id);if(marker){this.world.remove(marker.sprite);marker.texture.dispose();marker.sprite.material.dispose();this.entityBars.delete(id);}}
    for(const [id,sink] of this.sinkingMeshes){const p=(time-sink.start)/1650;sink.mesh.position.y=-p*72;sink.mesh.rotation.z=p*.5;sink.mesh.rotation.x=p*.16;if(p>=1){this.world.remove(sink.mesh);this.sinkingMeshes.delete(id);}}
    this.impactMeshes=this.impactMeshes.filter(effect=>{const p=(time-effect.start)/(effect.duration??760);if(p>=1){this.world.remove(effect.root);return false;}effect.root.scale.setScalar(1+p*.9);for(const child of effect.root.children){if(child instanceof THREE.Mesh){const velocity=child.userData.velocity as THREE.Vector3|undefined;if(velocity){child.position.addScaledVector(velocity,.016);velocity.y-=.45;const material=child.material as THREE.MeshStandardMaterial;material.opacity=Math.max(0,.72-p*.72);}else{const material=child.material as THREE.MeshBasicMaterial;material.opacity=Math.max(0,.75-p*.75);}}if(child instanceof THREE.PointLight)child.intensity=6*(1-p);}return true;});
    this.ring.visible=frame.selectedId!==null&&live.has(frame.selectedId);if(this.ring.visible){const e=frame.entities.find(x=>x.id===frame.selectedId)!;this.ring.position.set(e.x,3,e.y);this.ring.rotation.z=time*.001;}
    this.destinationRing.visible=!!frame.destination;if(frame.destination){this.destinationRing.position.set(frame.destination.x,3,frame.destination.y);const pulse=1+Math.sin(time*.006)*.18;this.destinationRing.scale.setScalar(pulse);}
    const shotSet=new Set(frame.shots);for(const s of frame.shots){let shot=this.shotMeshes.get(s);if(!shot){shot=new THREE.Group();const color=s.enemy?0xff6045:new THREE.Color(AMMO[s.ammo].color),core=s.ammo==="harpoon"?new THREE.Mesh(new THREE.ConeGeometry(3.8,18,7),new THREE.MeshStandardMaterial({color,emissive:color,emissiveIntensity:.65,metalness:.55,roughness:.26})):new THREE.Mesh(new THREE.SphereGeometry(4.6,12,9),new THREE.MeshStandardMaterial({color,emissive:color,emissiveIntensity:.48,metalness:.5,roughness:.3}));if(s.ammo==="harpoon")core.rotation.z=-Math.PI/2;const trail=new THREE.Mesh(new THREE.CylinderGeometry(1.2,2.4,s.ammo==="harpoon"?32:24,8),new THREE.MeshBasicMaterial({color,transparent:true,opacity:.5,depthWrite:false}));trail.rotation.z=Math.PI/2;trail.position.x=-12;shot.add(core,trail,new THREE.PointLight(color,s.enemy?2.7:2.1,90));this.shotMeshes.set(s,shot);this.world.add(shot);const muzzle=createMuzzleEffect(color),origin=s.enemy?{x:s.x,y:s.y,height:4}:this.playerMuzzlePosition(frame,s);muzzle.position.set(origin.x,origin.height,origin.y);muzzle.rotation.y=-Math.atan2(s.vy,s.vx);this.world.add(muzzle);this.impactMeshes.push({root:muzzle,start:time,duration:520});}const progress=clamp(1-s.ttl/1.8,0,1);shot.position.set(s.x,21+Math.sin(progress*Math.PI)*31,s.y);shot.rotation.y=-Math.atan2(s.vy,s.vx);}
    for(const [projectile,shot] of this.shotMeshes)if(!shotSet.has(projectile)){if(!projectile.hit&&projectile.ttl<=0){const splash=createWaterSplash();splash.position.set(shot.position.x,0,shot.position.z);this.world.add(splash);this.impactMeshes.push({root:splash,start:time,duration:900});}this.world.remove(shot);this.shotMeshes.delete(projectile);}
    const wakeSet=new Set(frame.wake);for(const sample of frame.wake){let wake=this.wakeMeshes.get(sample);if(!wake){wake=createWakePatch(sample.strength);wake.position.set(sample.x,0,sample.y);wake.rotation.y=-sample.angle;this.wakeMeshes.set(sample,wake);this.world.add(wake);}const life=clamp(sample.ttl/1.35,0,1);wake.scale.setScalar(1+(1-life)*.38);wake.traverse(o=>{if(o instanceof THREE.Mesh)(o.material as THREE.MeshBasicMaterial).opacity=life*(.12+.3*sample.strength);});}for(const [sample,wake] of this.wakeMeshes)if(!wakeSet.has(sample)){this.world.remove(wake);this.wakeMeshes.delete(sample);}
    const lootSet=new Set<number>();for(const l of frame.loot){lootSet.add(l.id);let root=this.lootMeshes.get(l.id);if(!root){root=createLootChest();this.lootMeshes.set(l.id,root);this.world.add(root);}root.position.set(l.x,5+Math.sin(time*.003+l.id)*5,l.y);root.rotation.y=time*.001;}
    for(const [id,mesh] of this.lootMeshes)if(!lootSet.has(id)){this.world.remove(mesh);this.lootMeshes.delete(id);}
    const islandLabelScale=clamp(1/this.smoothedZoom,.75,1.12);for(const marker of this.islandMarkers)marker.sprite.scale.set(118*islandLabelScale,24*islandLabelScale,1);
    this.resize();this.renderer.render(this.scene,this.camera);
  }

  private resize(){const width=this.canvas.clientWidth,height=this.canvas.clientHeight;if(!width||!height)return;const pr=Math.min(devicePixelRatio*this.quality.renderScale,1.8),w=Math.round(width*pr),h=Math.round(height*pr);if(this.canvas.width!==w||this.canvas.height!==h){this.renderer.setPixelRatio(pr);this.renderer.setSize(width,height,false);this.camera.aspect=width/height;this.camera.far=6500*this.quality.viewDistance;this.camera.updateProjectionMatrix();}}
  pointFromEvent(clientX:number,clientY:number){const rect=this.canvas.getBoundingClientRect();this.pointer.set(((clientX-rect.left)/rect.width)*2-1,-((clientY-rect.top)/rect.height)*2+1);this.raycaster.setFromCamera(this.pointer,this.camera);const plane=new THREE.Plane(new THREE.Vector3(0,1,0),0),point=new THREE.Vector3();return this.raycaster.ray.intersectPlane(plane,point)?{x:point.x,y:point.z}:null;}
  pickEntity(clientX:number,clientY:number){const rect=this.canvas.getBoundingClientRect();this.pointer.set(((clientX-rect.left)/rect.width)*2-1,-((clientY-rect.top)/rect.height)*2+1);this.raycaster.setFromCamera(this.pointer,this.camera);const hits=this.raycaster.intersectObjects([...this.entityMeshes.values()],true),direct=hits[0]?.object.userData.entityId as number|undefined;if(direct!==undefined)return direct;let nearest:number|null=null,best=84;for(const [id,mesh] of this.entityMeshes){const projected=mesh.position.clone().project(this.camera),screenX=rect.left+(projected.x+1)*rect.width/2,screenY=rect.top+(1-projected.y)*rect.height/2,distance=Math.hypot(clientX-screenX,clientY-screenY);if(distance<best){best=distance;nearest=id;}}return nearest;}
  dispose(){for(const marker of this.entityBars.values())marker.texture.dispose();this.renderer.dispose();this.scene.traverse(o=>{if(o instanceof THREE.Mesh){o.geometry.dispose();const materials=Array.isArray(o.material)?o.material:[o.material];materials.forEach(m=>m.dispose());}if(o instanceof THREE.Sprite)o.material.dispose();});}
}
